### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'rvl_cdip_dataset.csv'

### ISSUE THREAD

**Issue by SoumyaroopNandi** [shabie/docformer#14]
I cannot find the rvl_cdip_dataset.csv file in your repository. It gives me an error in line 69 of dataset_creation_for_docformer.py
Where do I find the rvl_cdip_dataset.csv file?

**Comment by uakarsh** [comment]
Dear @SoumyaroopNandi, the code in the examples is just for the representation purpose, which I ran by creating a custom CSV file and running the docformer model on it. In the "Usage" section of the ReadMe, the appropriate usage of the docformer model is mentioned. I hope this helps and let me know if you still have confusion. I would try to post more example codes so that, everything becomes more clear

**Comment by uakarsh** [comment]
As far as the dataset is concerned, I cannot share the dataset at this time, but I would try to post some sample dataset with examples, I think that, it would help
