### ISSUE TITLE
How to find rvl_cdip_dataset.csv?

### ISSUE THREAD

**Issue by SaynaEbrahimi** [shabie/docformer#24]
Hi,

Thank you for sharing your great work. Can you please also share your `rvl_cdip_dataset.csv` file or refer me to where I can find it? 

Thanks,
Sayna

**Comment by uakarsh** [comment]
Hi,

That was a test file, and I don't think, we would be able to share it, since it had some issues. But, I can give you a general idea, about how to use the DocFormer for your particular task at hand. 

I have mentioned it here, all you need to do is, download any of the document images dataset, containing/not containing labels (For unsupervised work), and then follow the steps here,

https://github.com/shabie/docformer/issues/23

Hope this helps, and do let us know if you need any more information.

**Comment by uakarsh** [comment]
Maybe, if the issue has been resolved, can we close this issue?
